# Generated by Django 3.0.2 on 2020-01-27 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'ordering': ['date_of_creation'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_join', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('date_of_birth', models.DateField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('liked_posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='sn_network.Post')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sn_network.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='users_like_it',
            field=models.ManyToManyField(blank=True, related_name='users_like_it', to='sn_network.User'),
        ),
    ]
