# Generated by Django 3.0.2 on 2020-01-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sn_network', '0003_auto_20200127_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_like_it',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_posts',
        ),
        migrations.AddField(
            model_name='post',
            name='users_likes',
            field=models.ManyToManyField(blank=True, to='sn_network.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='sn_network.User'),
        ),
    ]
