# Generated by Django 3.0.2 on 2020-01-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn_network', '0008_auto_20200129_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_likes',
            field=models.ManyToManyField(blank=True, related_name='like_it', to='sn_network.UserProfile'),
        ),
    ]
