# Generated by Django 3.0.2 on 2020-01-30 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sn_network.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(default=sn_network.utils.pretty_datetime)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('users_likes', models.ManyToManyField(blank=True, related_name='like_it', to='user_app.UserProfile')),
            ],
            options={
                'ordering': ['date_of_creation'],
            },
        ),
    ]
